# Generated by Django 2.0.5 on 2020-05-27 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='in_used',
            field=models.ManyToManyField(to='stores.Store'),
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.Store'),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Type'),
        ),
        migrations.AddField(
            model_name='modifier',
            name='extra_products',
            field=models.ManyToManyField(blank=True, related_name='extras', to='products.Product'),
        ),
        migrations.AddField(
            model_name='modifier',
            name='modification_items',
            field=models.ManyToManyField(blank=True, to='products.ModificationItems'),
        ),
        migrations.AddField(
            model_name='modifier',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='modifications', to='products.Product'),
        ),
        migrations.AddField(
            model_name='modifier',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.Store'),
        ),
    ]
