# Generated by Django 2.0.5 on 2020-05-31 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200527_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_icon', models.ImageField(null=True, upload_to='type_icon/')),
                ('category_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='type',
            name='in_used',
            field=models.ManyToManyField(blank=True, to='stores.Store'),
        )
        
    ]
