# Generated by Django 2.0.5 on 2020-05-31 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200531_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='type_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_icon',
            field=models.ImageField(null=True, upload_to='category_icon/'),
        ),
    ]
