# Generated by Django 2.0.5 on 2020-06-01 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200531_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='type_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='type_category', to='products.Category'),
        ),
    ]
