# Generated by Django 2.0.5 on 2020-06-21 16:15

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_storelocations'),
        ('products', '0006_product_in_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreUbicationStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_stock', models.PositiveIntegerField()),
                ('is_public', models.BooleanField(choices=[(0, 'private'), (1, 'public')], default=0)),
            ],
        ),
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('public', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='in_stock',
        ),
        migrations.AddField(
            model_name='storeubicationstock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_sells_me', to='products.Product'),
        ),
        migrations.AddField(
            model_name='storeubicationstock',
            name='stock_of',
            field=models.ManyToManyField(related_name='in_stock_products', to='address.StoreLocations'),
        ),
    ]
