# Generated by Django 2.0.5 on 2020-07-19 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cards',
            old_name='paypal_card_id',
            new_name='braintree_token',
        ),
    ]
