# Generated by Django 2.0.5 on 2020-07-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0002_auto_20200719_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='card_type',
            field=models.CharField(default='visa', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cards',
            name='last_four',
            field=models.CharField(default=1234, max_length=4),
            preserve_default=False,
        ),
    ]
