# Generated by Django 2.0.5 on 2020-07-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0004_auto_20200719_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
