# Generated by Django 2.0.5 on 2020-07-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0005_auto_20200719_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='card_holder_name',
            field=models.CharField(default='Anthony Taveras', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cards',
            name='customer_id',
            field=models.CharField(default=202786106, max_length=100),
            preserve_default=False,
        ),
    ]
