# Generated by Django 2.0.5 on 2020-07-19 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0006_auto_20200719_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='billing_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='Billing.BillingProfile'),
        ),
    ]
