# Generated by Django 2.0.5 on 2020-07-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0007_auto_20200719_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
