# Generated by Django 2.0.5 on 2020-05-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('discount_type', models.PositiveSmallIntegerField(default=1)),
                ('coupon_name', models.CharField(max_length=100)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('use_limit', models.PositiveIntegerField(null=True)),
                ('published', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
