# Generated by Django 2.0.5 on 2020-06-03 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_storemanagerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storemanagerprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
