# Generated by Django 2.0.5 on 2020-06-03 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200603_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storemanagerprofile',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'store_owner'), (2, 'store_staff')], default=2),
        ),
        migrations.AlterField(
            model_name='storemanagerprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores_manager_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
