# Generated by Django 2.0.5 on 2020-06-03 15:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200603_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='storemanagerprofile',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storemanagerprofile',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'store_owner'), (2, 'store_staff'), (3, 'delivery boy'), (4, 'admin')], default=2),
        ),
    ]
