# Generated by Django 2.0.5 on 2020-06-15 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_storemanagerprofile_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storemanagerprofile',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.StoreLocations'),
        ),
    ]
