# Generated by Django 2.0.5 on 2020-06-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200615_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='fav_stores',
            field=models.ManyToManyField(to='address.StoreLocations'),
        ),
    ]
