# Generated by Django 2.0.5 on 2020-06-19 14:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200618_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='storemanagerprofile',
            name='checked_notifications',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
