# Generated by Django 2.0.5 on 2020-06-21 16:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_storeoutdoorsellerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeoutdoorsellerprofile',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storeoutdoorsellerprofile',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
