# Generated by Django 2.0.5 on 2020-06-05 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_coupons_used_it'),
        ('order', '0003_auto_20200527_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='coupons',
        ),
        migrations.AddField(
            model_name='order',
            name='coupons',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='promotions.Coupons'),
        ),
    ]
