# Generated by Django 2.0.5 on 2020-06-05 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_orderitems_parentid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='parentId',
            new_name='parent_id',
        ),
    ]
