# Generated by Django 2.0.5 on 2020-06-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20200605_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'recibida'), (1, 'aceptada'), (2, 'completada'), (3, 'eliminada')], default=0),
        ),
    ]
