# Generated by Django 2.0.5 on 2020-06-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20200605_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'pagar en la puerta'), (1, 'pago electronico')], default=1),
        ),
    ]
