# Generated by Django 2.0.5 on 2020-06-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20200610_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'pagar en la puerta'), (1, 'pago electronico')], default=2),
        ),
    ]
