# Generated by Django 2.0.5 on 2020-06-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20200610_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'cancelada_cliente'), (1, 'cancelada_staff'), (2, 'pendiente'), (3, 'aceptada'), (4, 'preparando'), (5, 'to deliver'), (6, 'on delivery'), (7, 'completada')], default=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'pagar en la puerta'), (1, 'pago electronico')], default=1),
        ),
    ]
