# Generated by Django 2.0.5 on 2020-05-27 12:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo', django.contrib.postgres.fields.jsonb.JSONField(default={'set': 'False'})),
                ('street_line1', models.CharField(blank=True, max_length=800, verbose_name='Address 1')),
                ('street_line2', models.CharField(blank=True, max_length=800, verbose_name='Address 2')),
                ('city', models.CharField(blank=True, max_length=800, verbose_name='City')),
                ('locality', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, default='Republica Dominicana', max_length=800, verbose_name='State')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Home'), (2, 'Work'), (3, 'Other')], default=1, verbose_name='Type')),
                ('alias', models.CharField(max_length=40, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('delivery_instruction', models.CharField(blank=True, max_length=250, null=True)),
                ('user_address_text', models.CharField(blank=True, max_length=250, null=True)),
                ('selected', models.BooleanField(default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.Address')),
            ],
        ),
    ]
