# Generated by Django 2.0.5 on 2020-06-15 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_remove_store_address'),
        ('address', '0002_deliveryinfo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreLocations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.Address')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_location', to='stores.Store')),
            ],
        ),
    ]
