# Generated by Django 2.0.5 on 2020-05-27 12:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Pendiente de aceptar'), (2, 'Aceptada'), (3, 'Cancelada')], default=1)),
                ('sits_amount', models.PositiveSmallIntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_start', models.TimeField()),
                ('day_end', models.TimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('days', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HorariosType',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'week'), (2, 'weekend'), (3, 'special')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_img', models.ImageField(upload_to='images/')),
                ('profile_img', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=250)),
                ('about', models.CharField(max_length=800)),
                ('active', models.BooleanField(default=False)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='address.Address')),
                ('horarios', models.ManyToManyField(related_name='store_horarios', to='stores.Horarios')),
            ],
        ),
    ]
