# Generated by Django 2.0.5 on 2020-05-31 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20200527_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Comida'), (2, 'Supermercados'), (3, 'Medicina')], default=1),
        ),
    ]
