# Generated by Django 2.0.5 on 2020-05-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_auto_20200531_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='horarios',
            field=models.ManyToManyField(blank=True, related_name='store_horarios', to='stores.Horarios'),
        ),
    ]
