# Generated by Django 2.0.5 on 2020-06-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_auto_20200531_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Comida'), (2, 'mercados'), (3, 'salud')], default=1),
        ),
    ]
