# Generated by Django 2.0.5 on 2020-06-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_deliveryinfo_user'),
        ('stores', '0006_auto_20200603_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='address',
        ),
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.ManyToManyField(blank=True, to='address.Address'),
        ),
    ]
