# Generated by Django 2.0.5 on 2020-06-19 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_remove_store_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookers', to='address.StoreLocations'),
        ),
    ]
