# Generated by Django 2.0.5 on 2020-06-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_auto_20200619_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Comida'), (2, 'mercados'), (3, 'salud'), (4, 'public_general_unique_store')], default=1),
        ),
    ]
