# Generated by Django 2.0.5 on 2020-06-19 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_auto_20200527_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.StoreLocations'),
        ),
    ]
